security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\RefUser: plaintext
        App\Entity\RefEtablissement: plaintext
        App\Security\DatabaseUserProvider: plaintext

    providers:
        database:
            id: database_user_provider
        secured_provider:
            entity:
                class: App\Entity\RefUser
                property: login

    firewalls:
        main:
            anonymous: true
            provider: secured_provider
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login #^/demo/secured/login$
            security: false

        secured_area:
            pattern: ^/login
            lazy: false
            security: true
            user_checker: App\Security\DatabaseUserProvider
            provider:  database
            form_login:
                login_path: login
                check_path: login