security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\RefUser: plaintext
        App\Entity\RefEtablissement: plaintext
        App\Security\DatabaseUserProvider: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        database:
            id: database_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login/
            anonymous: true

        main:
            pattern: ^/
            provider: database
            form_login:
                login_path: /login/
                check_path: /login_check/
                username_parameter: form[login]
                password_parameter: form[password]
            #logout:
            #    path: ECECA_logout
            #    target: '%default_url_return%'

    access_control:
        - { path: ^/login/, roles: PUBLIC_ACCESS }
        - { path: ^/.*, roles: IS_AUTHENTICATED_FULLY }
