<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RefTypePrioritaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefTypePrioritaireRepository extends EntityRepository
{
}
