# Messages de l'application
parameters:
  erreurs:
    001: La taille du fichier ne doit pas dépasser 250Ko.
    002: Aucun résultat.
    003: Aucune campagne ouverte.
    004: Aucune donnée disponible pour cette zone.
    005: Aucune campagne ouverte.
    006: Identification échouée.
    007: Un fichier du même nom existe déjà.
  warning:
    001: Aucun détail sur l'établissement.
    002: Aucun résultat disponible.
    003: Répartition non disponible.
    004: Aucune campagne disponible.
    005: Répartition non disponible.
    006: Aucun établissement trouvé.
  alert:
    001: Veuillez remplir et valider le formulaire.
    002: Valeur invalide.
    003: Etablissement invalide.
    004: Veuillez saisir un destinataire.
    005: Académie invalide.
    006: Département invalide.
    007: Pas de concordance entre les valeurs saisies.
  info:
    001: Le fichier est importé avec succès.
    002: Echec d'import, voir le fichier de log.
    003: ATTENTION - Les établissements de type EREA et ERPD ne sont pas pris en compte dans les résultats
    004: ATTENTION - Les établissements de type EREA et ERPD ne sont pas pris en compte dans les tableaux de bord pour les élections ASS et ATE, et PEE.

  perimetre_vide_message: Votre établissement n'est pas référencé dans cette application concernant les élections aux conseils d'écoles et aux conseils d'administration (ECECA). Pour toute question complémentaire, vous pouvez contacter les correspondants ECECA de votre académie, dont vous trouverez les adresses mèls sur le site de diffusion d'Orléans
  perimetre_vide_lien_site: http://diff.in.ac-orleans-tours.fr/diff/t3/index.php?id=718
  message_deficit_confirm: Une ou plusieurs liste(s) a(ont) droit à un nombre de sièges supérieur au nombre de candidats qu'elle(s) a(ont) présentés :\n- dans le premier degré, un tirage au sort peut être organisé par le directeur d'école dans les 5 jours ouvrables qui suivent la proclamation des résultats \n- dans le second degré, les sièges demeurés vacants sont pourvus par des élections intervenant dans les mêmes conditions et dans un délai n'excédant pas quinze jours.
  message_candidat_titulaire: Par liste, le nombre total de candidats titulaires doit être inférieur ou égal au nombre de sièges à pourvoir.

  mess_warning:
    001: Aucun contact défini pour le moment
    002: Aucune fédération définie pour le moment
    003: Aucune organisation définie pour le moment

  mess_erreurs:
    001: Aucun établissement de ce type défini pour le moment dans la zone choisie
