### CONNEXION
ECECA_login:
  path:  /login/
  controller: App\Controller\IdentificationController::loginAction

ECECA_login_check:
  path:  /login_check/

ECECA_logout:
  path:  /logout/
  controller: App\Controller\IdentificationController::logoutAction

### TABLEAU DE BORD
ECECA_homepage:
  path:  /
  controller: App\Controller\TableauDeBordController::indexAction

ECECA_tableau_bord:
  path:  /tableauDeBord/
  controller: App\Controller\TableauDeBordController::indexAction

ECECA_ajax_getEtablissementsByNumDepartement:
  path:  /tableauDeBord/etabsByNumDept/
  controller: App\Controller\TableauDeBordController::getEtablissementsByNumDepartementAction
  methods: POST

ECECA_recherche_TableauDeBord:
  path:  /tableauDeBord/rechercheTdb/
  controller: App\Controller\TableauDeBordController::rechercheAction

ECECA_ajax_getRechercheEtablissementsByNumDepartement:
  path:  /tableauDeBord/rechercheEtabsByNumDept/
  controller: App\Controller\TableauDeBordController::getEtablissementsByNumDepartementAction

### RESULTATS
ECECA_resultats:
  path:  /{codeUrlTypeElect}/resultats/
  controller: App\Controller\ResultatController::indexAction

ECECA_retour_resultats:
  path:  /{codeUrlTypeElect}/resultats/retourLstRech/
  controller: App\Controller\ResultatController::retourListeEtablissementAction

ECECA_resultats_export_XLS:
  path:  /{codeUrlTypeElect}/{etablissementUai}/resultats/exportXLS/
  controller: App\Controller\ResultatController::exportResultatsXLSAction
  defaults:
    etablissementUai: tous

ECECA_resultats_export_XLS_complet:
  path:  /{codeUrlTypeElect}/resultats/exportXLSComplet/
  controller: App\Controller\ResultatController::exportResultatsXLSCompletAction

ECECA_resultats_export_CSV_detaille:
  path:  /{codeUrlTypeElect}/resultats/exportCompletCSVDetaille/
  controller: App\Controller\ResultatController::exportResultatsCSVCompletDetailleAction

ECECA_resultats_etablissement:
  path:  /{codeUrlTypeElect}/resultats/etablissement/{uai}/{fileUpload}/{retourLstRech}/{fromEdit}
  controller: App\Controller\ResultatController::consultationResultatsEtablissementAction
  defaults:
    fileUpload: 0
    retourLstRech: 0
    fromEdit: 0

ECECA_resultats_transmis:
  path:  /{codeUrlTypeElect}/resultats/transmis/{numDept}/
  controller: App\Controller\ResultatController::consultationResultatsTransmisZoneAction
  defaults:
    numDept: 0

ECECA_change_statut_resultats_etab:
  path:  /{codeUrlTypeElect}/{etablissementUai}/changeStatut/{etat}/{retourLstRech}/
  controller: App\Controller\ResultatController::changementEtatEleEtabAction
  defaults:
    retourLstRech: 0

ECECA_devalider_tirage_sort_resultats_etab:
  path:  /{codeUrlTypeElect}/{etablissementUai}/devalidationTirageAuSort/{retourLstRech}/
  controller: App\Controller\ResultatController::devalidationTirageAuSortEleEtabAction
  defaults:
    retourLstRech: 0

ECECA_devalid_change_statut_resultats_etab:
  path:  /{codeUrlTypeElect}/{etablissementUai}/changesStatut/{etat}/{retourLstRech}/
  controller: App\Controller\ResultatController::changementEtatEleEtabDevalidationAction
  defaults:
    retourLstRech: 0

ECECA_validation_resultats_masse:
  path: /massValidation/
  controller: App\Controller\ResultatController::massValidationAction
  methods: POST

### STATISTIQUES
ECECA_statistiques:
  path:  /{codeUrlTypeElect}/statistiques/
  controller: App\Controller\StatistiqueController::indexAction

ECECA_recherche_statistiques:
  path:  /{codeUrlTypeElect}/statistiques/
  controller: App\Controller\StatistiqueController::rechercheAction

ECECA_statistiques_export_XLS:
  path:  /{codeUrlTypeElect}/statistiques/exportXLS/
  controller: App\Controller\StatistiqueController::exportStatistiquesXLSAction

### SAISIE RESULTATS
ECECA_saisie_resultats_etab:
  path:  /saisieResultats/{codeUrlTypeElect}/{etablissementUai}/modifier/{retourLstRech}/
  controller: App\Controller\SaisieResultatController::editionAction
  defaults:
    retourLstRech: 0

ECECA_aide_nb_sieges:
  path:  /saisieResultats/aide/{typeElectionId}/{etablissementUai}
  controller: App\Controller\SaisieResultatController::aideNbSiegesAction

ECECA_saisie_nb_sieges_tirage_sort:
  path:  /saisieResultats/{codeUrlTypeElect}/{uai}/tirageAuSort/
  controller: App\Controller\SaisieResultatController::nbSiegesTirageAuSortAction

### COURRIEL
ECECA_relance_courriel:
  path:  /courriel/{typeElectionId}/{idZone}/
  controller: App\Controller\CourrielController::relanceAction

ECECA_masse_courriel:
  path: /masseCourriel/
  controller: App\Controller\CourrielController::massRelanceAction
  methods: POST

ECECA_courriel_export_XLS:
  path:  /{typeElectionId}/{idZone}/courriel/exportXLS/
  controller: App\Controller\CourrielController::exportEtablissementsSansMailXLSAction

ECECA_courriel_masse_export_XLS:
  path:  /courriel/exportMasseXLS/
  controller: App\Controller\CourrielController::exportMasseEtablissementsSansMailXLSAction

ECECA_envoi_courriel:
  path: /envoyerCourriel/
  controller: App\Controller\CourrielController::envoiAction

ECECA_masse_envoi_courriel:
  path: /envoyerMasseCourriel/
  controller: App\Controller\CourrielController::massEnvoiAction

ECECA_courriel_libre:
  path: /{codeUrlTypeElect}/envoyerCourrielLibre/
  controller: App\Controller\CourrielController::envoiLibreAction

ECECA_ajax_getAllAcademie:
  path:  /academies/liste/
  controller: App\Controller\CourrielController::findAllAcademieAction
  methods: POST

ECECA_ajax_getDepartementsByCodeAcademie:
  path:  /departements/byCodeAcademie/
  controller: App\Controller\CourrielController::findDepartementsByCodeAcademieAction
  methods: POST

ECECA_ajax_getEtablissementsByZoneAndUaiOrLibelle:
  path:  /etablissements/byZoneAndUaiOrLibelle/
  controller: App\Controller\CourrielController::findEtablissementsByZoneAndUaiOrLibelleAction
  methods: POST

ECECA_ajax_getEtablissementByUaiOrLibelle:
  path:  /etablissements/byUaiOrLibelle/
  controller: App\Controller\CourrielController::findEtablissementByUaiOrLibelleAction
  methods: POST

### PV
ECECA_creation_PV:
  path:  /{codeUrlTypeElect}/{etablissementUai}/creationPV/{statut}/
  controller: App\Controller\PVController::creerPVAction

ECECA_upload_PV: ## Toujours utilisé ?
  path:  /{codeUrlTypeElect}/{etablissementUai}/uploadPV/
  controller: App\Controller\PVController::indexAction

ECECA_do_upload:
  path:  /{codeUrlTypeElect}/{etablissementUai}/upload/
  controller: App\Controller\PVController::uploadAction

### STATISTIQUES PARTICIPATION
ECECA_recapitulatif_participation:
  path: /recapitulatifParticipation/{codeUrlTypeElect}
  controller: App\Controller\RecapitulatifParticipationController::indexAction

ECECA_recapitulatif_participation_export_XLS:
  path:  /recapitulatifParticipation/{codeUrlTypeElect}/exportXLS/
  controller: App\Controller\RecapitulatifParticipationController::exportXLSAction

### STATISTIQUES EDUCATION PRIORITAIRE
ECECA_recapitulatif_participation_detaillee:
  path: /recapitulatifParticipationDetaillee/{codeUrlTypeElect}
  controller: App\Controller\RecapitulatifParticipationDetailleeController::indexAction

ECECA_recapitulatif_participation_detaillee_export_XLS:
  path:  /recapitulatifParticipationDetaillee/{codeUrlTypeElect}/exportXLS/
  controller: App\Controller\RecapitulatifParticipationDetailleeController::exportXLSAction

### ARCHIVES
ECECA_archives:
  path:  /{codeUrlTypeElect}/archives/
  controller: App\Controller\ArchiveController::indexAction

ECECA_archives_export_XLS:
  path:  /{codeUrlTypeElect}/archives/exportXLS/
  controller: App\Controller\ArchiveController::exportStatistiquesXLSAction

### AJAX
ECECA_ajax_getAcaDepComByZone:
  path:  /etablissements/selectAcaDepCom/
  controller: App\Controller\AjaxController::findAcademieDepartementCommuneByZoneAction
  methods: POST

### CONTACTS
ECECA_contacts:
  path:  /contacts/
  controller: App\Controller\ContactController::indexAction

ECECA_contact_ajouter:
  path:  /contacts/ajouter/
  controller: App\Controller\ContactController::modifierContactAction

ECECA_contact_modifier:
  path:  /contacts/{contactId}/modifier/
  controller: App\Controller\ContactController::modifierContactAction

### FEDERATIONS
ECECA_federations:
  path:  /federations/
  controller: App\Controller\FederationController::indexAction

ECECA_federation_ajouter:
  path:  /federations/ajouter/
  controller: App\Controller\FederationController::modifierFederationAction

ECECA_federation_modifier:
  path:  /federations/{federationId}/modifier/
  controller: App\Controller\FederationController::modifierFederationAction

ECECA_federation_supprimer:
  path: /federations/{federationId}/supprimer/
  controller: App\Controller\FederationController::supprimerFederationAction
  methods: DELETE

### ORGANISATIONS
ECECA_organisations:
  path:  /organisations/
  controller: App\Controller\OrganisationController::indexAction

ECECA_organisation_ajouter:
  path:  /organisations/ajouter/
  controller: App\Controller\OrganisationController::modifierOrganisationAction

ECECA_organisation_modifier:
  path:  /organisations/{organisationId}/modifier/
  controller: App\Controller\OrganisationController::modifierOrganisationAction

### ETABLISSEMENT
ECECA_etablissement:
  path:  /etablissements/{page}/
  controller: App\Controller\EtablissementController::indexAction
  defaults:
    page: 1
  requirements:
    page:  \d*

ECECA_import:
  path:  /importRamsese/
  controller: App\Controller\EtablissementController::importRamseseAction

### CAMPAGNES
ECECA_campagnes:
  path:  /campagnes/
  controller: App\Controller\CampagneController::indexAction

ECECA_campagne_ajouter:
  path:  /campagnes/ajouter/
  controller: App\Controller\CampagneController::modifierAction

ECECA_campagne_modifier:
  path:  /campagnes/{campagneId}/modifier/
  controller: App\Controller\CampagneController::modifierAction

ECECA_campagne_archiver:
  path:  /campagnes/{campagneId}/archiver/
  controller: App\Controller\CampagneController::archiverAction

### RECHERCHE ETABLISSEMENT
ECECA_affichage_resultat_recherche_etablissements:
  path:  /rechercheEtablissementsResultat
  controller: App\Controller\RechercheEtablissementController::affichageEtablissementsAction
  methods: POST

ECECA_page_formulaire_recherche_etablissement:
  path: /rechercheEtablissements
  controller: App\Controller\RechercheEtablissementController::indexAction

ECECA_ouvrir_fermer_etablissement:
  path: /ouvrirFermerEtablissement/
  controller: App\Controller\RechercheEtablissementController::ouvrirFermerEtablissementAction
  methods: POST
