document.createElement("header"); 
document.createElement("footer"); 
document.createElement("section"); 
document.createElement("time"); 
document.createElement("nav"); 
document.createElement("article"); 
document.createElement("figure"); 
document.createElement("hgroup");
document.createElement("aside");
